name: Metrics
on:
  # Esegui l'aggiornamento ogni notte a mezzanotte
  schedule: [{cron: "0 0 * * *"}]
  # Permette di eseguire l'azione manualmente da GitHub
  workflow_dispatch:
  # Esegue l'azione quando fai un push sul branch principale
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Devi creare un Personal Access Token e salvarlo nei Secrets della repository come METRICS_TOKEN
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Opzioni base
          user: RMChannel
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome
          
          # Plugin per le Lingue
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
