name: Metrics
on:
  # Esegui l'aggiornamento ogni notte a mezzanotte
  schedule: [{cron: "0 0 * * *"}]
  # Permette di eseguire l'azione manualmente da GitHub
  workflow_dispatch:
  # Esegue l'azione quando fai un push sul branch principale
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Genera Statistiche Generali
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: RMChannel
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome
